# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddNewDepartment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewDepartment(object):
    def setupUi(self, NewDepartment):
        NewDepartment.setObjectName("NewDepartment")
        NewDepartment.resize(225, 246)
        self.centralwidget = QtWidgets.QWidget(NewDepartment)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 181, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_10.setObjectName("label_10")
        self.new_department_name = QtWidgets.QLineEdit(self.groupBox_2)
        self.new_department_name.setGeometry(QtCore.QRect(10, 40, 161, 20))
        self.new_department_name.setObjectName("new_department_name")
        self.new_department_adress = QtWidgets.QLineEdit(self.groupBox_2)
        self.new_department_adress.setGeometry(QtCore.QRect(10, 90, 161, 20))
        self.new_department_adress.setObjectName("new_department_adress")
        self.add_department = QtWidgets.QPushButton(self.centralwidget)
        self.add_department.setGeometry(QtCore.QRect(30, 170, 75, 23))
        self.add_department.setObjectName("add_department")
        self.cancel_add_department = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_add_department.setGeometry(QtCore.QRect(120, 170, 75, 23))
        self.cancel_add_department.setObjectName("cancel_add_department")
        NewDepartment.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewDepartment)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 225, 21))
        self.menubar.setObjectName("menubar")
        NewDepartment.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NewDepartment)
        self.statusbar.setObjectName("statusbar")
        NewDepartment.setStatusBar(self.statusbar)

        self.retranslateUi(NewDepartment)
        QtCore.QMetaObject.connectSlotsByName(NewDepartment)

    def retranslateUi(self, NewDepartment):
        _translate = QtCore.QCoreApplication.translate
        NewDepartment.setWindowTitle(_translate("NewDepartment", "Добавить отдел"))
        self.groupBox_2.setTitle(_translate("NewDepartment", "Новый отдел"))
        self.label_9.setText(_translate("NewDepartment", "Название отдела:"))
        self.label_10.setText(_translate("NewDepartment", "Адрес отдела:"))
        self.add_department.setText(_translate("NewDepartment", "Добавить"))
        self.cancel_add_department.setText(_translate("NewDepartment", "Отмена"))
