# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\resources\ShowDataWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowData(object):
    def setupUi(self, ShowData):
        ShowData.setObjectName("ShowData")
        ShowData.resize(400, 327)
        self.textEdit = QtWidgets.QTextEdit(ShowData)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 351, 251))
        self.textEdit.setObjectName("textEdit")
        self.label_data = QtWidgets.QLabel(ShowData)
        self.label_data.setGeometry(QtCore.QRect(20, 10, 181, 16))
        self.label_data.setObjectName("label_data")
        self.pushButton = QtWidgets.QPushButton(ShowData)
        self.pushButton.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ShowData)
        QtCore.QMetaObject.connectSlotsByName(ShowData)

    def retranslateUi(self, ShowData):
        _translate = QtCore.QCoreApplication.translate
        ShowData.setWindowTitle(_translate("ShowData", "Показать информацию"))
        self.label_data.setText(_translate("ShowData", "TextLabel"))
        self.pushButton.setText(_translate("ShowData", "Ок"))
