# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Turniket.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RFID(object):
    def setupUi(self, RFID):
        RFID.setObjectName("RFID")
        RFID.resize(150, 238)
        self.centralwidget = QtWidgets.QWidget(RFID)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 111, 151))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label.setObjectName("label")
        self.worker_id = QtWidgets.QComboBox(self.groupBox)
        self.worker_id.setGeometry(QtCore.QRect(10, 60, 69, 22))
        self.worker_id.setObjectName("worker_id")
        self.make_attendance = QtWidgets.QPushButton(self.groupBox)
        self.make_attendance.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.make_attendance.setObjectName("make_attendance")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 101, 16))
        self.label_2.setObjectName("label_2")
        RFID.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RFID)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 150, 21))
        self.menubar.setObjectName("menubar")
        RFID.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RFID)
        self.statusbar.setObjectName("statusbar")
        RFID.setStatusBar(self.statusbar)

        self.retranslateUi(RFID)
        QtCore.QMetaObject.connectSlotsByName(RFID)

    def retranslateUi(self, RFID):
        _translate = QtCore.QCoreApplication.translate
        RFID.setWindowTitle(_translate("RFID", "Турникет"))
        self.groupBox.setTitle(_translate("RFID", "Поставить явку"))
        self.label.setText(_translate("RFID", "id работника"))
        self.make_attendance.setText(_translate("RFID", "Поставить"))
        self.label_2.setText(_translate("RFID", "Это окно условно!!"))
